mongodb:
  service: mongodb
  user: mongodb
  group: mongodb

  # local path to a keyfile that will be copied over to the server
  # and added to mongodb.conf
  keyfile: null

  configPath: /etc/mongodb.conf
  keyfilePath: /etc/mongodb.keyfile

  config:
    port: 27017
    dbpath: /var/lib/mongodb
    logpath: /var/log/mongodb/mongodb.log
    logappend: 'true'
