- name: set hostname
  sudo: true
  hostname: name={{ inventory_hostname }}

- name: apt-get update
  sudo: true
  apt: update_cache=yes cache_valid_time=3600

- name: install packages
  sudo: true
  apt: pkg={{ item }}
  with_items:
    - python-pycurl # for ansible
    - python-pip # for ansible

- name: install python packages
  sudo: true
  pip: name={{ item }}
  with_items:
    - pymongo # for ansible
