- name: restart {{ mongodb.service }}
  sudo: true
  service: >
    name={{ mongodb.service }}
    state=restarted
  notify: wait for {{ mongodb.service }}

- name: wait for {{ mongodb.service }}
  wait_for: >
    port={{ mongodb.config.port }}
    delay=1
    timeout=60
