- name: add APT key
  sudo: true
  apt_key: >
    id=0x7F0CEB10
    url=http://docs.mongodb.org/10gen-gpg-key.asc
    state=present

- name: add repository
  sudo: true
  apt_repository: >
    repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
    update_cache=yes
    state=present

- name: prevent default mongodb autostart
  sudo: true
  copy: >
    content='ENABLE_MONGODB=no'
    dest=/etc/default/mongodb
    owner=root
    group=root
    mode=0644

- name: install package
  sudo: true
  apt: pkg=mongodb-10gen

- name: upload keyfile
  sudo: true
  copy: >
    src={{ mongodb.keyfile }}
    dest={{ mongodb.keyfilePath }}
    owner=mongodb
    group=mongodb
    mode=0600
  when: mongodb.keyfile
  notify: restart {{ mongodb.service }}

- name: generate config
  sudo: true
  template: >
    src=mongodb.conf.j2
    dest={{ mongodb.configPath }}
    owner=root
    group=root
    mode=0644
  notify: restart {{ mongodb.service }}

- name: generate upstart script
  sudo: true
  template: >
    src=upstart.conf.j2
    dest=/etc/init/{{ mongodb.service }}.conf
    owner=root
    group=root
    mode=0644
  notify: restart {{ mongodb.service }}

- name: create database directory
  sudo: true
  file: >
    path={{ mongodb.config.dbpath }}
    state=directory
    recurse=true
    owner={{ mongodb.user }}
    group={{ mongodb.group }}
    mode=0755

- name: create logs directory
  sudo: true
  file: >
    path={{ mongodb.config.logpath | dirname }}
    state=directory
    recurse=true
    owner={{ mongodb.user }}
    group={{ mongodb.group }}
    mode=0755
