- name: add APT key
  sudo: true
  apt_key: >
    id=0x7F0CEB10
    url=http://docs.mongodb.org/10gen-gpg-key.asc
    state=present

- name: add repository
  sudo: true
  apt_repository: >
    repo='deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen'
    update_cache=yes
    state=present

- name: install package
  sudo: true
  apt: pkg=mongodb-10gen

- name: upload keyfile
  sudo: true
  copy: >
    src={{ mongodb.keyFile }}
    dest=/etc/mongodb.keyfile
    owner=mongodb
    group=mongodb
    mode=0600
  when: mongodb.keyFile
  notify: restart mongodb

- name: generate config
  sudo: true
  template: >
    src=mongodb.conf.j2
    dest=/etc/mongodb.conf
    mode=0644
  notify: restart mongodb
