- name: fail if mongodb.config.replSet is not set
  fail: msg="mongodb.config.replSet is not set"
  when: mongodb.config.replSet is not defined

- name: flush handlers
  meta: flush_handlers

- name: initiate replica set
  mongodb_replica_set: >
    login_user={{ mongodb.admin_username }}
    login_password={{ mongodb.admin_password }}
    state=initiated

- name: create mongodb admin
  mongodb_user: >
    database=admin
    user={{ mongodb.admin_username }}
    password={{ mongodb.admin_password }}
    roles=dbAdminAnyDatabase,userAdminAnyDatabase,readWriteAnyDatabase,clusterAdmin

- name: generate ~/.mongorc.js
  template: >
    src=mongorc.js.j2
    dest=~/.mongorc.js
    mode=0644
