- name: fail if mongodb.config.replSet is not set
  fail: msg="mongodb.config.replSet is not set"
  when: mongodb.config.replSet is not defined

- name: flush handlers
  meta: flush_handlers

- name: initiate replica set
  mongodb_replica_set: >
    login_username={{ mongodb.admin_username }}
    login_password={{ mongodb.admin_password }}
    state=initiated
