- name: fail if mongodb.config.replSet is not set
  fail: msg="mongodb.config.replSet is not set"
  when: mongodb.config.replSet is not defined

- name: flush handlers
  meta: flush_handlers

- name: pre-check
  command: >
    /usr/bin/mongo --quiet --eval 'printjson(rs.isMaster().hosts.indexOf("{{ inventory_hostname }}:{{ mongodb.config.port }}") === -1)'
  register: pre_result
  changed_when: false
  delegate_to: "{{ groups['mongodb-primary'][0] }}"

- name: add secondary to replica set
  command: >
    /usr/bin/mongo --quiet --eval 'printjson(rs.add("{{ inventory_hostname }}:{{ mongodb.config.port }}").ok)'
  register: rs_result
  delegate_to: "{{ groups['mongodb-primary'][0] }}"
  when: pre_result.stdout == 'true'
